### ISSUE TITLE
AoiComponent.cs#L157 这里是笔误吗？

### ISSUE THREAD

**Issue by mustime** [qq362946/AOI#1]
https://github.com/qq362946/AOI/blob/f3dcb123250a6df3641ba673a2a3ada6d6481b20/ET-Component/AOI/AoiComponent.cs#L157

看上下文相关算法，这里貌似也应该是 `node.Link.XNode = _xLinks.AddBefore(cur, node);` 吧？

**Comment by l42111996** [comment]
https://github.com/qq362946/AOI/blob/f3dcb123250a6df3641ba673a2a3ada6d6481b20/ET-Component/AOI/AoiComponent.cs#L167

我感觉这里是笔误，上面的是正确的

**Comment by qq362946** [comment]
抱歉，这么久了才看到。我最近已经更新了算法，采用了新的方式，有时间您可以看一下。

**Comment by mustime** [comment]
赞一个，有兴趣写篇blog介绍一下新的方式吗？
