### ISSUE TITLE
实体的退出有数据没清除干净

### ISSUE THREAD

**Issue by m969** [qq362946/AOI#2]
[Program - 副本.txt](https://github.com/qq362946/AOI/files/6007257/Program.-.txt)

这个测试用例里，已经离开的 2 3 4 实体还可能会出现在moveKey的视野列表里

**Comment by qq362946** [comment]
感谢您提供的测试用例，确实是会产生一些无法删除的垃圾数据，是我编写的逻辑导致。
目前这个问题已经修复了。你可以再试试。
